name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v4

    #  Install dependencies
    - name: Install build tools
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential wget libfuse2

    # Set up Qt
    - name: Install Qt
      run: |
        sudo apt-get update
        sudo apt-get install -y qt5-qmake qtbase5-dev libqt5serialport5-dev

    # Install ctags
    - name: Install ctags
      run: |
        sudo apt-get install -y exuberant-ctags


    # Download appimagetool
    - name: Download appimagetool
      run: |
        wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
        chmod +x appimagetool-x86_64.AppImage

    # Build the project
    - name: Build project
      run: |
        ./build.py --prefix=$(pwd)/AppDir install

    # Prepare AppDir
    - name: Prepare AppDir
      run: |
        mkdir -p AppDir/
        cp gede_icon.png AppDir/
        cp gede.desktop   AppDir/
        chmod +x AppDir/bin/gede
        
    # Build AppImage
    - name: Build AppImage
      run: |
        ./appimagetool-x86_64.AppImage AppDir

    # Upload AppImage as an artifact
    - name: Upload AppImage
      uses: actions/upload-artifact@v4
      with:
        # Optional. Default is 'artifact'
        name: Gede-${{ github.ref_name }}.AppImage
        # A file, directory or wildcard pattern that describes what to upload
        path: Gede-*.AppImage
        
        # The desired behavior if no files are found using the provided path.
        # Available Options:
        #   warn: Output a warning but do not fail the action
        #   error: Fail the action with an error message
        #   ignore: Do not output any warnings or errors, the action does not fail
        # Optional. Default is 'warn'
        if-no-files-found:

        # Duration after which artifact will expire in days. 0 means using default retention.
        # Minimum 1 day.
        # Maximum 90 days unless changed from the repository settings page.
        # Optional. Defaults to repository settings.
        retention-days:

        # The level of compression for Zlib to be applied to the artifact archive.
        # The value can range from 0 to 9.
        # For large files that are not easily compressed, a value of 0 is recommended for significantly faster uploads.
        # Optional. Default is '6'
        #compression-level:

        # If true, an artifact with a matching name will be deleted before a new one is uploaded.
        # If false, the action will fail if an artifact for the given name already exists.
        # Does not fail if the artifact does not exist.
        # Optional. Default is 'false'
        #overwrite:

        # Whether to include hidden files in the provided path in the artifact
        # The file contents of any hidden files in the path should be validated before
        # enabled this to avoid uploading sensitive information.
        # Optional. Default is 'false'
        #include-hidden-files:
    


