name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make

    # Set up Qt
    - name: Install Qt
      run: |
        sudo apt-get update
        sudo apt-get install -y qt5-qmake qtbase5-dev libqt5serialport5-dev

    # Install ctags
    - name: Install ctags
      run: |
        sudo apt-get install -y exuberant-ctags

    # Build
    - name: Build
      run: |
        chmod a+x ./build.py
        ./build.py --build-all

